### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by Bart-Edelbroek** [ZahraPayandeh/Zahra_project#1]
Please improve readability of the `README.md`, see example below. Also, please remove the other `Readme.md` since they collide (you cannot have two identically named files in the GitHub repo).

For example instead of writing:

# Zahra_project
Project Title:  Nuclear Area Analysis using Python (Image Analysis and Statistical Analysis)
Aim
The aim of this project is to assess the nuclear area stability between two groups of nucleus images: Nucleus24 and Nucleus38. The project includes steps such as image loading, preprocessing, segmentation, contour detection, area measurement, statistical analysis, and result visualization.
Project Overview
This Python-based

You could do

# Zahra_project

Nuclear Area Analysis using Python (Image Analysis and Statistical Analysis)

## Aim

The aim of this project is to assess the nuclear area stability between two groups of nucleus images: Nucleus24 and Nucleus38. The project includes steps such as image loading, preprocessing, segmentation, contour detection, area measurement, statistical analysis, and result visualization.

## Project Overview

This Python-based ....

**Comment by Bart-Edelbroek** [comment]
Good improvement, but you should still improve the "Usage" section. There is an empty code block and you don't specify how one should run the Main.py script

**Comment by ZahraPayandeh** [comment]
Hi,
Thank you for your feedback,
I tried to edit all issues in the git hub parts according your comments.
Here is the link https://github.com/ZahraPayandeh/Zahra_project.
I realized just 2 of them were closed. i was wondering if you have checked the rest of them?
I hope they are acceptable now.
Best
Zahra


________________________________
From: Bart-Edelbroek ***@***.***>
Sent: Friday, November 1, 2024 11:25 AM
To: ZahraPayandeh/Zahra_project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ZahraPayandeh/Zahra_project] Improve README.md (Issue #1)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Please improve readability of the README.md, see example below. Also, please remove the other Readme.md since they collide (you cannot have two identically named files in the GitHub repo).

For example instead of writing:

Zahra_project

Project Title: Nuclear Area Analysis using Python (Image Analysis and Statistical Analysis)
Aim
The aim of this project is to assess the nuclear area stability between two groups of nucleus images: Nucleus24 and Nucleus38. The project includes steps such as image loading, preprocessing, segmentation, contour detection, area measurement, statistical analysis, and result visualization.
Project Overview
This Python-based

You could do

Zahra_project

Nuclear Area Analysis using Python (Image Analysis and Statistical Analysis)

Aim

The aim of this project is to assess the nuclear area stability between two groups of nucleus images: Nucleus24 and Nucleus38. The project includes steps such as image loading, preprocessing, segmentation, contour detection, area measurement, statistical analysis, and result visualization.

Project Overview

This Python-based ....
